services:
  - type: web
    name: hsk-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DBUrl
        sync: false
      - key: APIKey
        sync: false
      - key: BUNDEBUG
        value: "0"
      - key: DeepseekAPIKey
        sync: false
    plan: free